//Auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_USER = 'REGISTER_USER';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';


//CUSTOMER TYPES
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const GETALL_CUSTOMER = 'GETALL_CUSTOMER';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR';

//User Types
export const GETALL_USER = 'GETALL_USER';
export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';


//Approvers Types
export const CREATE_APPROVER = 'CREATE_APPROVER';
export const GETALL_CUSTOMERS_APPROVER = 'GETALL_CUSTOMERS_APPROVER';
export const GETALL_USERS_APPROVER = 'GETALL_USERS_APPROVER';
export const GET_CUSTOMER_BYUSER = 'GET_CUSTOMER_BYUSER';
export const APPROVER_ERROR = 'APPROVER_ERROR';

export const LOAD_APPROVER = 'LOAD_APPROVER';
export const APPROVER_LOGIN = 'APPROVER_LOGIN';
export const APPROVER_LOGIN_ERROR = 'APPROVER_LOGIN_ERROR';

